---
- name: Install OpenMax libraries
  ansible.builtin.apt:
    name: libomxil-bellagio0
    state: present

- name: Make config directory
  ansible.builtin.file:
    path: /etc/docker-stacks.d/jellyfin/config
    state: directory
    mode: "0750"

- name: Make compose directory
  ansible.builtin.file:
    path: /opt/docker-stacks.d/jellyfin/
    state: directory
    mode: "0750"
  register: remote_compose_directory


- name: Debug compose directory
  ansible.builtin.debug:
    var: remote_compose_directory

- name: Copy docker-compose.yml
  ansible.builtin.copy:
    src: "{{ role_path }}/files/jellyfin/docker-compose.yml"
    dest: "{{ remote_compose_directory.path }}"
    mode: "0640"

- name: Install pip3
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install Pip docker modules
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose>=1.7.0,<2.0.0

- name: Docker Compose Up
  community.docker.docker_compose:
    project_src: "{{ remote_compose_directory.path }}"
  register: output

- name: Debug compose
  ansible.builtin.debug:
    var: output
