---
version: "3.4"

networks:
  default:
    name: traefik_proxy

services:
  traefik:
    image: traefik:latest
    container_name: tr
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/docker-stacks.d/traefik/letsencrypt:/letsencrypt"
    command:
      - "--log.level=${LOG_LEVEL}"
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.cloudflareresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflareresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflareresolver.acme.email=${CLOUDFLARE_EMAIL}"
      - "--certificatesresolvers.cloudflareresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.cloudflareresolver.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      #dashboard
      traefik.enable: true
      traefik.http.routers.traefik-api.rule: Host(`traefik.${ROOT_DOMAIN}`)
      traefik.http.routers.traefik-api.entryPoints: websecure
      traefik.http.routers.traefik-api.tls: true
      traefik.http.routers.traefik-api.tls.certresolver: cloudflareresolver
      traefik.http.routers.traefik-api.tls.domains[0].main: "${ROOT_DOMAIN}"
      traefik.http.routers.traefik-api.tls.domains[0].sans: "*.${ROOT_DOMAIN}"
      traefik.http.routers.traefik-api.service: api@internal
      traefik.http.routers.traefik-api.middlewares: dashboardauth@docker
      # redirect all http to https
      traefik.http.routers.http-catchall.rule: hostregexp(`{host:.+}`)
      traefik.http.routers.http-catchall.entrypoints: web
      traefik.http.routers.http-catchall.middlewares: redirect-to-https@docker
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      #basic auth
      traefik.http.middlewares.dashboardauth.basicauth.users: "user:{SHA}W6ph5Mm5Pz8GgiULbPgzG37mj9g=" # user:password at the moment it's literally "user:password"