---
version: "3.4"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Europe/London
    volumes:
      - /etc/docker-stacks.d/jellyfin/config:/config
      - /mnt/medialib/media/tv-shows/:/data/tvshows
      - /mnt/medialib/media/movies/:/data/movies
      - /mnt/medialib/media/anime/:/data/anime
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/video10:/dev/video10 # hardware accelleration - V4L2
      - /dev/video11:/dev/video11 # hardware accelleration - V4L2
      - /dev/video12:/dev/video12 # hardware accelleration - V4L2
    restart: unless-stopped
